[package]
name = "Adapter"
edition = "2024.beta"
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]
published-at = "0x5fee448eda1dd26b9fe1c8d72ee5228631c4b337c995d1e62dc8e61ef4aa30b9"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
DeepBook = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/deepbook", rev = "testnet" }
DCA = { local = "../dca" }

[addresses]
adapter = "0x5fee448eda1dd26b9fe1c8d72ee5228631c4b337c995d1e62dc8e61ef4aa30b9"
std = "0x1"
sui = "0x2"
deepbook = "0xdee9"
dca = "0x8cff310615dd198bb64af09efcf1bc54bd6a71bcc2fe2a1c8302b6f76f8ee427"