[package]
name = "Adapter"
edition = "2024.beta"
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]
published-at = "0x3223cf2259ad386fce4ec9dcb5df862ad338a6d00578abf3bbc0172d9850c590"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet", override = true }
DeepBook = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/deepbook", rev = "mainnet", override = true }
DCA = { local = "../dca" }

[addresses]
adapter = "0x8ff90cb0c620d9e62eefbf1da08d62d229d0282de8858424314e230ecda5e6bc"
std = "0x1"
sui = "0x2"
deepbook = "0xdee9"
dca = "0x33d51e66410b5d98fdd013d16194ab35b43d5b8fc76523876cd5f971c52084dd"