[package]
name = "Adapter"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/mainnet" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
DeepBook = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/deepbook", rev = "framework/mainnet" }
DCA = { local = "../dca" }
CetusClmm = { local = "../interfaces/cetus/cetus_clmm" }
Cetus = { local = "../interfaces/cetus/cetus" }

[addresses]
adapter = "0x0"
std = "0x1"
sui = "0x2"
deepbook = "0xdee9"